spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_POST}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      username: ${SPRING_DATA_MONGODB_USER}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      authentication-database: ${SPRING_DATA_MONGODB_AUTH}